### ISSUE TITLE
error setting agent address to mobile number

### ISSUE THREAD

**Issue by weihongchua** [Nexmo/comms-router#91]
When setting the agent address to mobile number, encounter the following error:
[note: real number is manually masked from the log]

curl -X PUT http://localhost:8080/comms-router-web/api/routers/my-router/agents/esagent1 -H 'Content-Type:application/json' -d'{"address”:”xxxxxxxxx”,”capabilities":{"language":["en","es"]}}'
Unrecognized field "address”:”xxxxxxxxx”,”capabilities" (class com.softavail.commsrouter.api.dto.arg.CreateAgentArg), not marked as ignorable (2 known properties: "address", "capabilities"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@251f1384; line: 1, column: 50] (through reference chain: com.softavail.commsrouter.api.dto.arg.CreateAgentArg["address”:”xxxxxxxxx”,”capabilities"]

**Comment by angel-popov** [comment]
Looks like double quotes are not from ascii table.
This one works
`curl -X PUT http://localhost:8080/comms-router-web/api/routers/router/agents/esagent1 -H 'Content-Type:application/json' -d'{"address":"xxxxxxxxx","capabilities":{"language":["en","es"]}}'`
