### ISSUE TITLE
It should not be allowed to add skill with no domain

### ISSUE THREAD

**Issue by angel-popov** [Nexmo/comms-router#95]
Create new skill with domain null.
Result:pass
Request:curl -s -X POST 'http://192.168.1.166:8080/comms-router-web/api/routers/router-ivr/skills' -H 'Content-type:application/json' -d "{\"description\":\"description\",\"domain\":null,\"multivalue\":true}"
Response:{"ref":"PRcS0rTjGAgrtnR1AODIt"}

**Comment by ikrustev** [comment]
Should be fixed now.
